Gallery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'gallery'),
]

Profile/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name = 'profile'),
]

ProjectYunie/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('Profile/', include('Profile.urls')),
    path('Gallery/', include('Gallery.urls')),
    path('Schedule/', include ('SimulasiModel.urls')),
]

SimulasiModel/urls.py
from django.urls import path, re_path
from . import views

app_name = 'activity'
urlpatterns = [
    path('', views.index, name = 'schedule'),
    path('create/', views.create, name = 'create'),
    re_path('delete/(?P<delete_id>.*)/', views.delete, name='delete'),
]

Gallery/models.py
from django.db import models

# Create your models here.

Profile/models.py
from django.db import models

# Create your models here.

SimulasiModel/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Schedule (models.Model) :
    date = models.DateField()
    time = models.TimeField()
    activity = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.Activity

    


    

SimulasiModel/forms.py
from django import forms
from datetime import datetime

class Schedule_Form(forms.Form):
    activity = forms.CharField(max_length=100)
    date = forms.DateField( widget = forms.SelectDateWidget(attrs={'id' : 'datepicker'}))
    time = forms.TimeField( widget = forms.TimeInput(attrs = {'id' : 'timepicker'}))
    place = forms.CharField(max_length=100)
    category = forms.CharField(max_length=100)

Gallery/views.py
from django.shortcuts import render

def index (request):
    return render(request, 'Gallery/Gallery.html')

Profile/views.py
from django.shortcuts import render

def index (request):
    return render(request, 'Profile/Profile.html')

ProjectYunie/views.py
from django.shortcuts import render  

def index (request):
    return render(request, 'Home.html')

SimulasiModel/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Schedule_Form
from .models import Schedule
from datetime import datetime

# Create your views here.
def index(request):
    listJadwal = {
        'listJadwal' : Schedule.objects.all()
    }
    return render(request, 'SimulasiModel/Model.html', listJadwal)


def create(request):
    createJadwal = Schedule_Form(request.POST or None)
    if (request.method == 'POST' and createJadwal.is_valid()) :
        simpen = Schedule(
            activity = createJadwal.data['activity'],
            date = datetime.strptime('{} {} {} {}'.format(createJadwal.data['date_month'], createJadwal.data['date_day'], createJadwal.data['date_year'], createJadwal.data['time']), '%m %d %Y %H:%M'),
            time = createJadwal.data['time'],
            place = createJadwal.data['place'],
            category = createJadwal.data['category'],
        )
        simpen.save()
        return HttpResponseRedirect("/Schedule/")
    create_Jadwal ={
        'schedule_form' : createJadwal,
    }
    return render(request, 'SimulasiModel/create.html', create_Jadwal)

def delete(request, delete_id):
    Schedule.objects.filter(id = delete_id).delete()
    return HttpResponseRedirect("/Schedule/")

Gallery/templates/Gallery/Gallery.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/Style_Profile_Yunie_revisi.css' %}">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/abyssinica" type="text/css">
    <title>Yunie Debora's Profile</title>    
  </head>

    <body>
        <nav class="navbar navbar-expand-md fixed-top">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'index' %}" target=_self > Home</a>
                    </li>
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'profile' %}" target=_self > Profile</a>
                    </li>
                    <li class="nav-item active" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'gallery' %}" style="font-size:medium; ">Gallery<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'activity:schedule' %}" style="font-size:medium; ">Schedule<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>


        <div class = "container-fluid">
            <div class = "row">
                    <div class= "col">
                    <div class= "row justify-content-center">
                        <h1 align = "center"><br><br>PICTURE OF ME<br></h1>
                    </div>
                    <div class="row">
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/lJKIqqN.jpg" class = "image" style = "width:300px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/OtJ2eyX.jpg" class = "image" style = "width:300px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/yEb83u7.jpg" class = "image" style = "width:300px;"></center></div>
                    </div>
                    <div class="row">
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/cYVqNZy.jpg" class = "image" style = "width:300px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/7vjn8gN.jpg" class = "image" style = "width:300px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/AMSt9wb.jpg" class = "image" style = "width:300px;"></center></div>
                    </div>
                    <div class="row">
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/rWPlFix.jpg" class = "image" style = "width:400px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/FvaKTrv.jpg" class = "image" style = "width:400px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/ntSsShs.jpg" class = "image" style = "width:400px;"></center></div>
                    </div>
                    <div class="row">
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/Ze0LrZX.jpg" class = "image" style = "width:400px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/SNxFWME.jpg" class = "image" style = "width:400px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/R109kVa.jpg" class = "image" style = "width:400px;"></center></div>
                    </div>
                    <div class="row">
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/P49tiDt.jpg" class = "image" style = "width:400px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/IOIcnfi.jpg" class = "image" style = "width:400px;"></center></div>
                        <div class="col" style ="padding :1%;"><center><img srcset="https://i.imgur.com/b5i3AcP.jpg" class = "image" style = "width:400px;"></center></div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

Profile/templates/Profile/Profile.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/Style_Profile_Yunie_revisi.css' %}">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/abyssinica" type="text/css">
    <title>Yunie Debora's Profile</title>    
  </head>

    <body>
        
        <nav class="navbar navbar-expand-md fixed-top">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'index' %}" target=_self >Home</a>
                    </li>
                    <li class="nav-item active" style="margin-left: 15%">
                    <a class="nav-link" href="" > Profile <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="#pendidikan" target=_self > Education</a>
                    </li>
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="#pengalaman" target=_self > Experiences</a>
                    </li> 
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="#skill" target=a_blank >Skills</a>
                    </li>
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="#about&contact" target=_self >Contact</a>
                    </li>
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'gallery' %}" target=_self >Gallery</a>
                    </li>
                    <li class="nav-item" style="margin-left: 15%">
                    <a class="nav-link" href="{% url 'activity:schedule' %}" target=_self >Schedule</a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class = "container-fluid">
            <div class = "row">
                <div class = "col" id ="background1">
                    <br><br><br>
                    <center><img srcset="https://i.imgur.com/JMSzjPT.jpg" class="rounded-circle" style = "border: 5px solid #101313; box-sizing: border-box; top: 112px; width:300px;height:300px;"></center>
                    <br><br>

                    <center><div class = "textBox" style = "width:43%; height:28%; min-width: 300px;">
                    <h1 align = "center">Hello! I’m Yunie Debora</h1>
                    <p align = "center">
                        I’m 19 years old girl who currently studying in Computer Science<br>
                        Faculty, Universitas Indonesia. Information System is my major, I learn <br>
                        about programming, and also learn about Management and Business.  
                    </p>
                    </div></center>
                    <br>
                </div>
            </div>

            <section id="pendidikan">
            <div class="row">
                <div class = "col">
                <div class = "row justify-content-center">
                    <h1 align = "center"><strong><br><br> EDUCATION <br></strong></h1>
                </div>
                <div class ="row">
                <div class="col"> 
                    <img srcset = "https://i.imgur.com/ZK5Tvqd.jpg" class= "image" style = "width:75%; margin-left:20%; margin-top:20%;">
                </div>
                <div class="col">
                    <div class="timeline">
                        <div class="container left">
                            <div class="content">
                                <div class="row"><div class = "col"><img src = "https://i.imgur.com/Z7Jr1hL.png" style = "width:75px;"></div>
                                <div class = "col"><h2>SDN 116/IV<br>Kota Jambi</h2>
                                <p>2006 - 2012</p></div></div>
                            </div>
                        </div>
                        <div class="container right">
                            <div class="content">
                                <div class="row"><div class = "col"><img src = "https://i.imgur.com/yddJltk.png" style = "width:75px;border-radius:25%;"></div>
                                <div class = "col"><h2>SMP N 5 <br>Kota Jambi</h2>
                                <p>2012 - 2015</p></div></div>
                            </div>
                        </div>
                        <div class="container left">
                            <div class="content">
                                <div class="row"><div class = "col"><img src = "https://i.imgur.com/OE44CqL.png" style = "width:75px;border-radius:25%;"></div>
                                <div class = "col"><h2>SMA N 1<br>Kota Jambi</h2>
                                <p>2015 - 2018</p></div></div>
                            </div>
                        </div>
                        <div class="container right">
                            <div class="content">
                                <div class="row"><div class = "col"><img src = "https://i.imgur.com/s3QG6NI.png" style = "width:75px;"></div>
                                <div class = "col"><h2>Universitas<br>Indonesia</h2>
                                <p>On Going</p></div></div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                </div>
            </div>
            </section>
            
            <setion id="pengalaman">
            <div class="row">
                <div class="col">
                <div class="row justify-content-center">
                    <h1 align = "center"><strong><br><br> Experiences <br><br></strong></h1>
                </div>
                <div class= "row">
                <div class ="experiences">
                <div class = "col"><img srcset ="https://i.imgur.com/RuHruIq.png" class = "image" style = "width:500px;"></div>
                <div class = "col">
                    <p style = "font-size:24px; margin-left:630px; margin-top:-310px;" ><strong>
                        * Secretary of SMP N 5 Kota Jambi Student Council <br>(2013/2014)<br><br>
                        * Staff of MPK SMA N 1 Kota Jambi (2015/2016)<br><br>
                        * Vice Chairman of MPK SMAN 1 Kota Jambi (2016/2017)<br><br>
                        * Staff of BEM Fasilkom UI, Art and Culture Department<br>(2018/2019)
                    </strong></p>
                </div>
                <div class = "col">
                    <p style = "font-size:24px; margin-left:1340px; margin-top:-335px;"><strong>
                        * PSM UI Paragita 2018<br><br>
                        * Staff of Event Division DUIUJ 2019<br><br>
                        * Staff of Public Relation Educare 2019<br><br>
                        * Staff of FnB CompFest 2019<br><br>
                        * Chasier of Rich Fried Chicken Jambi (June - August 2019)
                    </strong></p>
                </div>
                </div>
                </div>
                </div>
            </div>
            </setion>

            <section id="skill">
            <div class="row" id="background2">
                <div class="col">
                <div class = "row justify-content-center">
                <h1><strong><br><br> Skills <br><br></strong></h1>
                </div>
                
                <div class="row" style="padding-bottom:5%;">
                <div class = "col" style = "text-align: right; padding-right:5%" >
                    <div class="textBox" style="background: rgb(56, 30, 5); width:20%; opacity:0.5;"></div>
                    <h1 style="font-size: 35px;  text-decoration: underline;"><strong>Hard Skills</strong></h1>
                    <p style="font-size: 20px;"><strong>Python &emsp;&emsp; 8/10<br><br>
                        Java&ensp;&emsp;&emsp;&emsp;7/10<br><br>Ms. Office&ensp;&ensp;9/10<br><br>English&ensp;&emsp;&emsp;8/10</strong></p>
                </div>
                <div class = "col" style = "padding-left:5%">
                    <div class="textBox" style="background: rgb(56, 30, 5); width:20%; opacity:0.5;"></div>
                    <h1 style="font-size: 35px;text-decoration: underline;"><strong>Soft Skills</strong></h1>
                    <p style="font-size: 20px;"><strong>Responsibility&emsp; 9/10<br><br>
                        Discipline&emsp;&emsp;&emsp;9/10<br><br>Punctual &emsp;&emsp;&emsp;9/10<br><br>Creative&ensp;&emsp;&emsp;&emsp;8/10</strong></p>
                </div>
                </div>
                </div>
            </div>
            </section>

            <section id = "about&contact">
            <div class = "row" id= "background3" >
                <div class = "col" style="padding-top: 5%; padding-left:5%; padding-bottom:5%;">
                    <div class = "textBox">
                    <center><h1 style = "font-size:64px;"><strong>About Me</strong></h1></center>
                    <div class = "line" style="width:110%; height:0.5%; margin-left:-5%;"></div>
                    <div class="row" style="padding: 10%;">
                        <img src = "https://i.imgur.com/lAplTqy.png" class = "image" style = "width:120px;">
                        <p style = "font-size:28px;"><strong> <br>June, 20 2000</strong></p>
                    </div>
                    <div class="row" style="padding-left:10%;">
                        <img src = "https://i.imgur.com/PRKIfJK.png" class = "image" style = "width:120px;">
                        <p style = "font-size:25px;"><strong><br>&ensp; yuniedebora20@gmail.com</strong></p>
                    </div>
                    <div class="row" style="padding-left:10%; padding-top:5%; padding-bottom:5%;">
                        <img src = "https://i.imgur.com/VehAkOo.png" class = "image" style = "width:120px;">
                        <p style = "font-size:25px;"><strong><br>&ensp; Mandor Goweng 82 <br>Kukusan, Beji, Depok</strong></p>
                    </div>
                    </div>
                </div>
                    
                <div class = "col" style="padding-top: 5%; padding-right:5%; padding-bottom:5%;">
                    <div class = "textBox" style="width:100%;"><center>
                        <center><h1 style = "font-size:64px;"><strong>Contact Me</strong></h1></center>
                        <div class = "line" style="width:110%; height:0.5%; margin-left:-5%;"></div>
                        <div style = "padding-top:39.5%; padding-bottom:39.5%;">
                        <a href="https://www.facebook.com/profile.php?id=100018171343251" target="_blank">
                        <img src="https://i.imgur.com/fWT6dkL.png" class = "image" style = "width:75px; " >
                        </a>
                        &emsp;
                        <a href="https://www.instagram.com/yuniedeboraaa/" target="_blank">
                        <img src="https://i.imgur.com/kSTA35d.png" class = "image" style = "width:75px; " >
                        </a>
                        &emsp;
                        <a href="https://wa.me/+685210658282" target="_blank">
                        <img src="https://i.imgur.com/6UacqdG.png" class = "image" style = "width:75px;  " >
                        </a>
                        &emsp;
                        <a href="https://www.linkedin.com/in/yunie-debora-176b74177/" target="_blank">
                        <img src="https://i.imgur.com/KYDrwE2.png" class = "image" style = "width:75px; " >
                        </a>
                        </div>
                    </center></div>
                </div>
            </section> </div>
        </div>
    </body>
            
            
        

SimulasiModel/templates/SimulasiModel/Model.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/Style_Profile_Yunie_revisi.css' %}">
    <title>Yunie Debora's Profile</title>
    
  </head>
  

  <body>
    <nav class="navbar navbar-expand-md fixed-top">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'index' %}" target=_self > Home </a>
                </li>
                <li class="nav-item" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'profile' %}" target=_self > Profile</a>
                </li>
                <li class="nav-item" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'gallery' %}" target=_self > Gallery</a>
                </li>
                <li class="nav-item active" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'activity:schedule' %}" style="font-size:medium; ">Schedule<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <a href="{% url 'activity:create' %}" class="btn btn-light btn-lg" role="button" style ="margin-top:10%; margin-left:39%;" >Create a Schedule</a>

    <div class = "row">
      <div class = "col">
          <h1 style="text-align: center; margin-top:5%;">List of Yunie's Schedule</h1>
          <div class = "row justify-content-center" style = "margin-top :5%;">
            <div class = "col"><p style="text-align: center;"><strong> DATE</strong></p></div>
            <div class = "col"><p style="text-align: center;"><strong>ACTIVITY </strong></p></div>
            <div class = "col"><p style="text-align: center;"><strong>TIME</strong></p></div>
            <div class = "col"><p style="text-align: center;"><strong>PLACE</strong></p></div>
            <div class = "col"><p style="text-align: center;"><strong>CATEGORY</strong></p></div>
          </div>
          <div class = line style = "width:95%; margin-left:2%;"></div>
          
            {% for activity in listJadwal%}
            <div class = "row justify-content-center" style = "margin-top :3%;">
              <div class = "col"><p style="text-align: center;"> {{activity.date}}</p></div>
              <div class = "col"><p style="text-align: center;">{{activity.activity}} </p></div>
              <div class = "col"><p style="text-align: center;"> {{activity.time}} </p></div>
              <div class = "col"><p style="text-align: center;">{{activity.place}} </p></div>
              <div class = "col"><p style="text-align: center;">{{activity.category}} </p></div>
            </div>
            <a href="{% url 'activity:delete' activity.id %}" class="btn btn-light btn-xs" role="button" style="margin-left:5%;" >Delete</a>
            {% endfor %}  
      </div>
    </div>

  </body>
</html>

SimulasiModel/templates/SimulasiModel/create.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/Style_Profile_Yunie_revisi.css' %}">
    <title>Yunie Debora's Profile</title>
    
  </head>

  <body>    
      <div class = "row"  >
            <div class = "col">
              <div class = "row justify-content-center">
                <div class = "textBox" style = "margin-top:10%;">
                  <h1 style ="text-align: center"> Create a Schedule</h1>
                </div>
              </div>
              <div class = "row justify-content-center">
                <div class = "textBox" style = "margin-top:5%;">
                  <form method = "POST">
                    {% csrf_token %}
                    <table>
                      {{schedule_form.as_table}}
                    </table>
                    <center><button type = "submit" value="Add" >Save</button></center>
                  </form>
                </div>
              </div>
              <a href="{% url 'activity:schedule' %}" class="btn btn-light btn-lg" role="button" style ="margin-top:3%; margin-left:45%;" >Back</a>
            </div>
        </div>
    </body>
    </html>
      

templates/Home.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/Style_Profile_Yunie_revisi.css' %}">
    <title>Yunie Debora's Profile</title>
    
  </head>
  

  <body>
    <nav class="navbar navbar-expand-md fixed-top">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'index' %}" style="font-size:medium; ">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'profile' %}" target=_self > Profile</a>
                </li>
                <li class="nav-item" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'gallery' %}" target=_self > Gallery</a>
                </li>
                <li class="nav-item" style="margin-left: 15%">
                <a class="nav-link" href="{% url 'activity:schedule' %}" target=_self > Schedule</a>
                </li>
            </ul>
        </div>
    </nav>


    <div class= "container-fluid" style = "background :#AB7A4C; height:100vw; position:fixed;">
    <div class = "row justify-content-center" style ="padding-top:0.5%;">
      <img srcset="https://i.imgur.com/L7imalu.jpg"class= "rounded-circle" style ="width:20%; margin-top:5%;position:relative; z-index:2;">
      <div class = "row;" style ="padding-left:15%; padding-right:15%;">
      <div class = "textBox" style="text-align: center; margin-top:-10%;">
      <img src="https://i.imgur.com/OVvvm5N.png" style = "width:28%; padding-top:7vw; position:relative; z-index:2;" >
      <h1 style="font-size:24px;margin-top:1vw; margin-bottom:1vw;">You will see Yunie Debora's Profile 
        <br> a singer who studies in Universitas Indonesia<br> Want to know more about her, please click the button below</h1>
      <a href="{% url 'profile' %}" class="btn btn-light btn-lg" role="button" >Let's Go!</a>
      </div>
      </div>
    </div>
    </div>
  </body>
</html>